const fs=require('fs'),path=require('path'),adoc=require('@asciidoctor/core')();
const root=path.resolve(__dirname,'..'),src=path.join(root,'curriculum/asciidoc/courses/llm-knowledge-graph-construction'),out=path.join(root,'site');
fs.mkdirSync(out,{recursive:true});fs.cpSync(src,path.join(out,'content'),{recursive:true});fs.cpSync(path.join(root,'exercises'),path.join(out,'exercises'),{recursive:true,filter:p=>!p.includes('/.git')});
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const title=p=>fs.readFileSync(p,'utf8').match(/^= (.+)$/m)?.[1]||path.basename(p);
const sort=a=>a.sort((x,y)=>x.localeCompare(y,undefined,{numeric:true}));
let lessons=[],modules=[];
for(const m of sort(fs.readdirSync(path.join(src,'modules')))){const dir=path.join(src,'modules',m);const group={title:title(path.join(dir,'module.adoc')),lessons:[]};for(const l of sort(fs.readdirSync(path.join(dir,'lessons')))){const file=path.join(dir,'lessons',l,'lesson.adoc');if(!fs.existsSync(file))continue;const item={title:title(file),file,rel:path.relative(src,file),name:`lesson-${lessons.length+1}.html`};lessons.push(item);group.lessons.push(item);}modules.push(group);}
const css=`*{box-sizing:border-box}body{margin:0;color:#243349;background:#f7f9fc;font:17px/1.65 system-ui,sans-serif}aside{position:fixed;width:290px;inset:0 auto 0 0;background:#132b3d;color:white;padding:28px 22px;overflow:auto}aside a{color:#cfe7ef;display:block;text-decoration:none;padding:6px 8px;border-radius:5px;font-size:14px}aside a.active,aside a:hover{background:#285167;color:white}aside h3{font-size:14px;margin:22px 0 6px}main{margin-left:290px;padding:42px 6vw;max-width:1200px}h1,h2,h3{line-height:1.25}h1{font-size:36px}a{color:#086d91}img,video,iframe{max-width:100%}pre{background:#eaf0f5;padding:20px;overflow:auto;border-radius:8px;font-size:14px}code{font-family:ui-monospace,monospace}table{border-collapse:collapse;width:100%}td,th{padding:12px;border:1px solid #cbd5e1}.notice,.admonitionblock{background:#e5f1f4;border-left:4px solid #1688a0;padding:14px 20px;margin:20px 0}.pager{display:flex;justify-content:space-between;gap:20px;border-top:1px solid #ccc;padding-top:20px;margin-top:40px}.imageblock{text-align:center;margin:24px 0}details{background:#edf2f7;padding:10px 16px;margin:16px 0}summary{cursor:pointer;font-weight:600}@media(max-width:800px){aside{position:static;width:auto}main{margin:0;padding:24px}h1{font-size:28px}}`;
fs.writeFileSync(path.join(out,'style.css'),css);
function render(file){const rel=path.relative(src,path.dirname(file)).split(path.sep).join('/');let html=adoc.convertFile(file,{safe:'unsafe',to_file:false,standalone:false,attributes:{imagesdir:`content/${rel}`,'repository-raw':'exercises','repository-blob':'exercises',branch:'.','repository-link':'exercises/','instance-scheme':'neo4j+s','instance-ip':'YOUR_NEO4J_HOST','instance-host':'YOUR_NEO4J_HOST','instance-boltPort':'7687','instance-database':'neo4j','instance-username':'neo4j','instance-password':'YOUR_PASSWORD'}});html=html.replace(/href="(?:https:\/\/graphacademy.neo4j.com)?(\/courses?\/[^"#]*)"/g,(_,p)=>`href="https://graphacademy.neo4j.com${p}"`).replace(/href="(?:\.\/)?data\//g,`href="content/${rel}/data/`);html=html.replace(/<div class="admonitionblock tip (solution|hint)">([\s\S]*?)<\/table>\s*<\/div>/g,(_,role,body)=>`<details><summary>${role==='solution'?'Show solution':'Show hint'}</summary><table>${body.replace(/^\s*<table>\s*/, '')}</table></details>`);return html.replaceAll('genai-fundamentals_1-generative-ai_1-what-is-genaii.pdf','genai-fundamentals_1-generative-ai_1-what-is-genai.pdf');}
function page(name,heading,body,index){const nav=modules.map(m=>`<h3>${esc(m.title)}</h3>`+m.lessons.map(l=>`<a class="${l.name===name?'active':''}" href="${l.name}">${esc(l.title)}</a>`).join('')).join('');const pager=index===undefined?'':`<nav class="pager"><a href="${index?lessons[index-1].name:'index.html'}">← ${index?'Previous lesson':'Course overview'}</a>${index<lessons.length-1?`<a href="${lessons[index+1].name}">Next lesson →</a>`:'<a href="index.html">Course overview →</a>'}</nav>`;fs.writeFileSync(path.join(out,name),`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(heading)} · Local GraphAcademy</title><link rel="stylesheet" href="style.css"></head><body><aside><h2>GraphAcademy<br><small>Local course reader</small></h2><a href="index.html">Course overview</a>${nav}<hr><a href="exercises/">Exercise files</a></aside><main><h1>${esc(heading)}</h1>${body}${pager}</main></body></html>`);}
page('index.html',title(path.join(src,'course.adoc')),`<div class="notice">Downloaded from Neo4j’s official repositories. All ${lessons.length} lessons, images, quizzes, and bundled PDFs are available locally. Quiz answers are shown in the source; expand the hints and solutions below each question. Hosted sandboxes, certification, and external tools require online services and your own credentials.</div>${render(path.join(src,'course.adoc'))}<p><a href="${lessons[0].name}">Start the course →</a></p>`);
lessons.forEach((l,i)=>page(l.name,l.title,render(l.file),i));fs.writeFileSync(path.join(root,'manifest.json'),JSON.stringify(lessons.map(l=>({...l,file:path.relative(root,l.file)})),null,2));console.log(`Built ${lessons.length} lessons in ${out}`);
